version: '*'
services: 
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app